version: "3.7"
services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: gokipedia
      MYSQL_PASSWORD: gokipedia
      MYSQL_DATABASE: image_gokipedia
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      DB_HOST: tcp(db:3306)
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
    networks:
      - backend

  # Api Service
  api:
    build:
      context: ./
      dockerfile: ./docker/build/golang/Dockerfile
    environment:
      CORS_ALLOWED_ORIGINS: "http://localhost:8000,http://localhost:5672"
      API_PORT: "8080"
      MYSQL_USER: gokipedia
      MYSQL_PASSWORD: gokipedia
      MYSQL_DATABASE: image_gokipedia
      DB_HOST: tcp(db:3306)
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_ERLANG_COOKIE: rabbitmq_cookie
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_PORT: 5672
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go:rw
    networks:
      - backend

networks:
  backend:
    driver: "bridge"