// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "c36441e0723978afb491e3630bb73c23"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"379215a1bd990f2651699ed931a724ed": "1f8b08000000000000ffb25174f1770e890c7055c828c9cdb1e3b2c9484d4cb1e352505050b029c92cc949b553f0c8cf4d55b0d187f0b86cf4212a6c92f2532aa10a5332cb202c10a8ae56d0732f4a4d2dc9cc4b57a8ad85a8d0872b41556c536097969f9f66a35f6087acd0461f6c3a200000ffff2724bb8e9d000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("templateBox", "../templates")
		b.SetResolver("home.html", packr.Pointer{ForwardBox: gk, ForwardPath: "379215a1bd990f2651699ed931a724ed"})
	}()
	return nil
}()
